-- Add missing columns to vendor_products table
ALTER TABLE vendor_products 
ADD COLUMN IF NOT EXISTS category VARCHAR(100),
ADD COLUMN IF NOT EXISTS subcategory VARCHAR(100),
ADD COLUMN IF NOT EXISTS tertiary_category VARCHAR(100),
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS images JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS original_price DECIMAL(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS length DECIMAL(8,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS width DECIMAL(8,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS height DECIMAL(8,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS weight DECIMAL(8,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS brand VARCHAR(100),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();